# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBooking.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addBooking(object):
    def setupUi(self, addBooking):
        addBooking.setObjectName("addBooking")
        addBooking.setWindowModality(QtCore.Qt.NonModal)
        addBooking.resize(562, 782)
        addBooking.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.groupBox = QtWidgets.QGroupBox(addBooking)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 481, 191))
        self.groupBox.setStyleSheet("font: 57 11pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.username = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setObjectName("username")
        self.horizontalLayout_4.addWidget(self.username)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.rut_user = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rut_user.sizePolicy().hasHeightForWidth())
        self.rut_user.setSizePolicy(sizePolicy)
        self.rut_user.setObjectName("rut_user")
        self.horizontalLayout_5.addWidget(self.rut_user)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(addBooking)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 440, 188, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setStyleSheet("font: 57 11pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.desc = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.desc.setObjectName("desc")
        self.horizontalLayout_3.addWidget(self.desc)
        self.label_6 = QtWidgets.QLabel(addBooking)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 331, 61))
        self.label_6.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight: bold;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(addBooking)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 300, 461, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.checkin = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.checkin.setStyleSheet("background-color : #CDCDCD;\n"
"color: rgb(0,0,0);")
        self.checkin.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 28), QtCore.QTime(0, 0, 0)))
        self.checkin.setTime(QtCore.QTime(0, 0, 0))
        self.checkin.setCalendarPopup(True)
        self.checkin.setTimeSpec(QtCore.Qt.LocalTime)
        self.checkin.setDate(QtCore.QDate(2020, 12, 28))
        self.checkin.setObjectName("checkin")
        self.horizontalLayout_2.addWidget(self.checkin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.checkout = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.checkout.setStyleSheet("background-color : #CDCDCD;\n"
"color: rgb(0,0,0);")
        self.checkout.setCalendarPopup(True)
        self.checkout.setDate(QtCore.QDate(2020, 12, 28))
        self.checkout.setObjectName("checkout")
        self.horizontalLayout_2.addWidget(self.checkout)
        self.precio = QtWidgets.QPushButton(addBooking)
        self.precio.setGeometry(QtCore.QRect(380, 560, 121, 51))
        self.precio.setObjectName("precio")
        self.cancelar = QtWidgets.QPushButton(addBooking)
        self.cancelar.setGeometry(QtCore.QRect(220, 560, 111, 51))
        self.cancelar.setObjectName("cancelar")

        self.retranslateUi(addBooking)
        QtCore.QMetaObject.connectSlotsByName(addBooking)

    def retranslateUi(self, addBooking):
        _translate = QtCore.QCoreApplication.translate
        addBooking.setWindowTitle(_translate("addBooking", "Reserva"))
        self.groupBox.setTitle(_translate("addBooking", "Cliente "))
        self.label_2.setText(_translate("addBooking", "Nombre :"))
        self.username.setText(_translate("addBooking", "User name"))
        self.label_3.setText(_translate("addBooking", "Rut :"))
        self.rut_user.setText(_translate("addBooking", "Rut user"))
        self.label_5.setText(_translate("addBooking", "Descuento %"))
        self.label_6.setText(_translate("addBooking", "Agregar  Reserva "))
        self.label_4.setText(_translate("addBooking", "Check-In"))
        self.label.setText(_translate("addBooking", "Check-Out"))
        self.precio.setText(_translate("addBooking", "Disponibilidad"))
        self.cancelar.setText(_translate("addBooking", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addBooking = QtWidgets.QDialog()
    ui = Ui_addBooking()
    ui.setupUi(addBooking)
    addBooking.show()
    sys.exit(app.exec_())
