# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabs(object):
    def setupUi(self, tabs):
        tabs.setObjectName("tabs")
        tabs.resize(1300, 729)
        tabs.setMinimumSize(QtCore.QSize(1300, 550))
        tabs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(tabs)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(tabs)
        self.tabWidget.setMinimumSize(QtCore.QSize(2, 0))
        self.tabWidget.setStyleSheet("QTabBar::tab:selected {\n"
"    background: #3B83BD\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: #FFFFFF\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    min-width: 200px\n"
"}\n"
"\n"
"QTabBar::tab::selected {\n"
"    min-width: 200px\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Calendar = QtWidgets.QWidget()
        self.Calendar.setObjectName("Calendar")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Calendar)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem, 8, 2, 1, 1)
        self.lcd = QtWidgets.QLCDNumber(self.Calendar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd.sizePolicy().hasHeightForWidth())
        self.lcd.setSizePolicy(sizePolicy)
        self.lcd.setStyleSheet("font: 57 41pt \"Ubuntu\";")
        self.lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd.setLineWidth(20)
        self.lcd.setMidLineWidth(10)
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd.setObjectName("lcd")
        self.gridLayout_2.addWidget(self.lcd, 6, 1, 1, 1)
        self.reservas_tab = QtWidgets.QPushButton(self.Calendar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservas_tab.sizePolicy().hasHeightForWidth())
        self.reservas_tab.setSizePolicy(sizePolicy)
        self.reservas_tab.setStyleSheet("background-color: #3B83BD;\n"
"font-size: 18px;\n"
"/*border-radius: 8px;*/\n"
"color: #FFFFFF;")
        self.reservas_tab.setObjectName("reservas_tab")
        self.gridLayout_2.addWidget(self.reservas_tab, 10, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 8, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 9, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 9, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.calendarWidget_5 = QtWidgets.QCalendarWidget(self.Calendar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_5.sizePolicy().hasHeightForWidth())
        self.calendarWidget_5.setSizePolicy(sizePolicy)
        self.calendarWidget_5.setStyleSheet("background-color : #CDCDCD;\n"
"color: rgb(0,0,0);")
        self.calendarWidget_5.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_5.setObjectName("calendarWidget_5")
        self.verticalLayout_5.addWidget(self.calendarWidget_5)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 8, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem4, 10, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 8, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 11, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem7, 10, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 5, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 7, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem10, 6, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Calendar, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setStyleSheet("font: 57 11pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_5.addWidget(self.label_27)
        self.search = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setObjectName("search")
        self.horizontalLayout_5.addWidget(self.search)
        self.buscar = QtWidgets.QPushButton(self.tab_2)
        self.buscar.setObjectName("buscar")
        self.horizontalLayout_5.addWidget(self.buscar)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("image: url(:/prefijoNuevo/imageUse/user.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rut = QtWidgets.QLabel(self.tab_2)
        self.rut.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.rut.setObjectName("rut")
        self.gridLayout_4.addWidget(self.rut, 1, 2, 1, 1)
        self.contacto = QtWidgets.QLabel(self.tab_2)
        self.contacto.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.contacto.setObjectName("contacto")
        self.gridLayout_4.addWidget(self.contacto, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 1, 1, 1)
        self.telefono = QtWidgets.QLabel(self.tab_2)
        self.telefono.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.telefono.setObjectName("telefono")
        self.gridLayout_4.addWidget(self.telefono, 2, 2, 1, 1)
        self.nombre = QtWidgets.QLabel(self.tab_2)
        self.nombre.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.nombre.setObjectName("nombre")
        self.gridLayout_4.addWidget(self.nombre, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 5, 1, 1, 1)
        self.procedencia = QtWidgets.QLabel(self.tab_2)
        self.procedencia.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.procedencia.setObjectName("procedencia")
        self.gridLayout_4.addWidget(self.procedencia, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 1, 1, 1)
        self.correo = QtWidgets.QLabel(self.tab_2)
        self.correo.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.correo.setObjectName("correo")
        self.gridLayout_4.addWidget(self.correo, 3, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.eliminar = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eliminar.sizePolicy().hasHeightForWidth())
        self.eliminar.setSizePolicy(sizePolicy)
        self.eliminar.setStyleSheet("background-color: #FF0000;\n"
"font-size: 18px;\n"
"/*border-radius: 8px;*/\n"
"color: #FFFFFF;")
        self.eliminar.setObjectName("eliminar")
        self.gridLayout_5.addWidget(self.eliminar, 0, 2, 1, 1)
        self.editR = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editR.sizePolicy().hasHeightForWidth())
        self.editR.setSizePolicy(sizePolicy)
        self.editR.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"font-size: 18px;\n"
"color: #FFFFFF;")
        self.editR.setObjectName("editR")
        self.gridLayout_5.addWidget(self.editR, 1, 1, 1, 1)
        self.update = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        self.update.setStyleSheet("background-color: #00BB2D;\n"
"font-size: 18px;\n"
"/*border-radius: 8px;*/\n"
"color: #FFFFFF;")
        self.update.setObjectName("update")
        self.gridLayout_5.addWidget(self.update, 0, 0, 1, 1)
        self.sendEmail = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendEmail.sizePolicy().hasHeightForWidth())
        self.sendEmail.setSizePolicy(sizePolicy)
        self.sendEmail.setStyleSheet("background-color: #3B83BD;\n"
"font-size: 18px;\n"
"/*border-radius: 8px;*/\n"
"color: #FFFFFF;")
        self.sendEmail.setObjectName("sendEmail")
        self.gridLayout_5.addWidget(self.sendEmail, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem14, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 861, 64))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 57 18pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.fecha = QtWidgets.QDateEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fecha.sizePolicy().hasHeightForWidth())
        self.fecha.setSizePolicy(sizePolicy)
        self.fecha.setStyleSheet("background-color : #CDCDCD;\n"
"color: rgb(0,0,0);")
        self.fecha.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 28), QtCore.QTime(0, 0, 0)))
        self.fecha.setTime(QtCore.QTime(0, 0, 0))
        self.fecha.setCalendarPopup(True)
        self.fecha.setTimeSpec(QtCore.Qt.LocalTime)
        self.fecha.setDate(QtCore.QDate(2020, 12, 28))
        self.fecha.setObjectName("fecha")
        self.horizontalLayout_2.addWidget(self.fecha)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_date = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setStyleSheet("font: 57 18pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_date.setObjectName("label_date")
        self.gridLayout_7.addWidget(self.label_date, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 79, 801, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidgetC = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetC.sizePolicy().hasHeightForWidth())
        self.tableWidgetC.setSizePolicy(sizePolicy)
        self.tableWidgetC.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetC.setObjectName("tableWidgetC")
        self.tableWidgetC.setColumnCount(0)
        self.tableWidgetC.setRowCount(0)
        self.tableWidgetC.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidgetC.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetC.verticalHeader().setDefaultSectionSize(50)
        self.tableWidgetC.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidgetC)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 221, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("font: 57 14pt \"Ubuntu\";\n"
"font-weight:bold;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 590, 165, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edp = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.edp.setStyleSheet("background-color: #3B83BD;\n"
"font-size: 18px;\n"
"/*border-radius: 8px;*/\n"
"color: #FFFFFF;")
        self.edp.setObjectName("edp")
        self.horizontalLayout_3.addWidget(self.edp)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.tableWidgetCab = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetCab.setGeometry(QtCore.QRect(10, 350, 211, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetCab.sizePolicy().hasHeightForWidth())
        self.tableWidgetCab.setSizePolicy(sizePolicy)
        self.tableWidgetCab.setObjectName("tableWidgetCab")
        self.tableWidgetCab.setColumnCount(0)
        self.tableWidgetCab.setRowCount(0)
        self.tableWidgetCab.horizontalHeader().setMinimumSectionSize(57)
        self.tableWidgetCab.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetCab.verticalHeader().setVisible(False)
        self.tableWidgetCab.verticalHeader().setDefaultSectionSize(67)
        self.tableWidgetCab.verticalHeader().setMinimumSectionSize(21)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(tabs)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(tabs)
        tabs.setTabOrder(self.reservas_tab, self.search)
        tabs.setTabOrder(self.search, self.buscar)
        tabs.setTabOrder(self.buscar, self.tableWidget)
        tabs.setTabOrder(self.tableWidget, self.calendarWidget_5)

    def retranslateUi(self, tabs):
        _translate = QtCore.QCoreApplication.translate
        tabs.setWindowTitle(_translate("tabs", "Igmava"))
        self.reservas_tab.setText(_translate("tabs", "Reservar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calendar), _translate("tabs", "Calendario"))
        self.label_27.setText(_translate("tabs", "Rut:"))
        self.buscar.setText(_translate("tabs", "Buscar"))
        self.rut.setText(_translate("tabs", "19358005-K"))
        self.contacto.setText(_translate("tabs", "Ninguno"))
        self.label.setText(_translate("tabs", "Nombre:"))
        self.label_17.setText(_translate("tabs", "Rut:"))
        self.telefono.setText(_translate("tabs", "1231231231"))
        self.nombre.setText(_translate("tabs", "Sergio"))
        self.label_23.setText(_translate("tabs", "Procedencia:"))
        self.label_19.setText(_translate("tabs", "Telefono:"))
        self.label_25.setText(_translate("tabs", "Contacto:"))
        self.procedencia.setText(_translate("tabs", "Valdivia"))
        self.label_21.setText(_translate("tabs", "Correo:"))
        self.correo.setText(_translate("tabs", "polo@gmail.com"))
        self.eliminar.setText(_translate("tabs", "Eliminar"))
        self.editR.setText(_translate("tabs", " Reservas usuario"))
        self.update.setText(_translate("tabs", "Actualizar"))
        self.sendEmail.setText(_translate("tabs", "Enviar correo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tabs", "Clientes"))
        self.label_3.setText(_translate("tabs", "Cabañas disponibles"))
        self.label_4.setText(_translate("tabs", "Fecha:"))
        self.label_date.setText(_translate("tabs", "TextLabel"))
        self.label_5.setText(_translate("tabs", "Observaciones:"))
        self.edp.setText(_translate("tabs", "Editar precio "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tabs", "Cabañas"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabs = QtWidgets.QWidget()
    ui = Ui_tabs()
    ui.setupUi(tabs)
    tabs.show()
    sys.exit(app.exec_())
